import type { Topology } from '../api/types';
import { glyphSvg } from './glyphs';
import type { Scene } from './layout';

/**
 * Export the auto-generated scene as a FossFLOW / Isoflow model (the JSON
 * FossFLOW's "Open" menu accepts), so a diagram can be hand-polished there.
 * Schema per fossflow@1.0.5 `schemas/model.ts`. Isoflow's tile y axis points
 * up, so y is negated. Secrets are never part of the scene, so never exported.
 */
export function toFossflowModel(topo: Topology, scene: Scene) {
  const glyphs = [...new Set(scene.nodes.map((n) => n.glyph))];
  const colors = new Map<string, string>();
  const colorId = (value: string) => {
    if (!colors.has(value)) colors.set(value, `c${colors.size}`);
    return colors.get(value)!;
  };
  const placeable = scene.nodes.filter((n) => n.kind !== 'ip');
  const items = placeable.map((n) => ({
    id: n.id,
    name: n.label,
    description: [n.sublabel, ...n.badges.map((b) => b.label)].filter(Boolean).join(' · '),
    icon: `kg-${n.glyph}`,
  }));
  const viewItems = placeable.map((n) => ({
    id: n.id,
    tile: { x: Math.round(n.tile.x + n.size.w / 2), y: -Math.round(n.tile.y + n.size.h / 2) },
  }));
  const rectangles = scene.zones.map((z) => ({
    id: z.id,
    color: colorId(z.color),
    from: { x: z.from.x, y: -z.from.y },
    to: { x: z.to.x, y: -z.to.y },
  }));
  const connectors = scene.connectors
    .filter((c) => scene.byId.has(c.from) && scene.byId.has(c.to) && c.kind !== 'ingress')
    .map((c) => ({
      id: c.id,
      description: c.label ?? '',
      color: colorId(c.kind === 'parent' ? '#868e96' : '#ff7a45'),
      width: 10,
      style: c.kind === 'parent' ? 'DASHED' : 'SOLID',
      anchors: [
        { id: `${c.id}:a`, ref: { item: c.from } },
        { id: `${c.id}:b`, ref: { item: c.to } },
      ],
    }));
  for (const c of scene.connectors.filter((x) => x.kind === 'ingress')) {
    connectors.push({
      id: c.id,
      description: c.label ?? '',
      color: colorId('#e9ecef'),
      width: 6,
      style: 'DOTTED',
      anchors: [
        { id: `${c.id}:a`, ref: { item: 'internet' } },
        { id: `${c.id}:b`, ref: { item: c.to } },
      ],
    });
  }
  return {
    version: '',
    title: topo.vaultName,
    description: 'Generated by Kurogane auto-layout',
    colors: [...colors.entries()].map(([value, id]) => ({ id, value })),
    icons: glyphs.map((g) => ({
      id: `kg-${g}`,
      name: g,
      url: `data:image/svg+xml;utf8,${encodeURIComponent(glyphSvg(g, '#343a40'))}`,
      collection: 'kurogane',
      isIsometric: false,
    })),
    items,
    views: [
      {
        id: 'kurogane-auto',
        name: 'Topology (auto)',
        lastUpdated: new Date().toISOString(),
        items: viewItems,
        rectangles,
        connectors,
        textBoxes: [],
      },
    ],
  };
}
